# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# Linting: xclip -sel c <.github/workflows/testing.yml # https://rhysd.github.io/actionlint/

on:
  push:
    branches: [ 'trunk', 'next', 'wip/**' ]
    # tags:   [ 'v[0-9]+.[0-9]+.[0-9]+*' ]
  pull_request:
    branches: [ 'trunk', 'next' ]

jobs:

  MakeCheck:
    runs-on: ubuntu-latest
    steps:
    - { uses: actions/checkout@v4.1.1, with: { fetch-depth: 0, submodules: recursive, github-server-url: 'https://github.com' } }
    - run: git fetch -f --tags          # Fix actions/checkout#290
    - run: git describe --always --long
    - run: make check

  Ping-IRC:
    needs: [MakeCheck]
    runs-on: ubuntu-latest
    steps:
    - { uses: actions/checkout@v4.1.1,	with: { fetch-depth: 0 } } # Fix actions/checkout#290
    - run: git fetch -f --tags && git describe --always --long
    - name: Check Jobs
      run: |
        echo '${{ needs.MakeCheck.result }}'
        [[ ${{ needs.MakeCheck.result }}    =~ success|skipped ]]
    - name: Ping IRC
      if: ${{ always() && !env.ACT }}
      run: |
        R='${{ github.repository }}' && R=${R#*/}
        B='${{ github.ref }}' && B=${B#refs/heads/}
        S='${{ job.status }}' && URL='${{ github.event.head_commit.url }}'
        A='${{ github.actor }}' && B="$(git branch --show-current)"
        MSG=$(git log -1 --format='%s')
        .github/workflows/ircbot.py -q -j "#Anklang" -R "$R" -U "$A" -D "$B" -S "$S" "$MSG" "$URL"
